### ISSUE TITLE
`:visible` in routes

### ISSUE THREAD

**Issue by xbili** [keajs/kea-example#1]
Is the `:visible` parameter in the `/todos` route used in this example?

https://github.com/keajs/kea-example/blob/a71ad02ae900819b4e8ae55590100e97dd09c2ea/app/scenes/routes.js#L11

**Comment by mariusandra** [comment]
Hey, it's not used. Actually the entire codebase was rather ancient (in JS standards) and needed some upgrades.

So I now upgraded the code to use react-router v4 (among other upgrades) and rewrote parts the todo list app to use urls for the 3 states (all, active, completed).

**Comment by xbili** [comment]
Got it!

Thanks for the work btw! This is pretty awesome :)
