### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by danielmariz** [keajs/kea-example#2]
I'm trying writing unit tests in my app for actions, reducers, selectors and sagas using Kea but having a lot of issues dragging the process. As you don't have a well documented lib and your examples are simple, you must provide a more complex example maybe using interaction with local storage and add unit tests for your components.

**Comment by mariusandra** [comment]
Hi, I added a sample test here: https://github.com/keajs/kea-example/blob/master/app/scenes/homepage/logic.test.js

**Comment by danielmariz** [comment]
Cool
