### ISSUE TITLE
Please update to work with latest keajs

### ISSUE THREAD

**Issue by kn666** [keajs/kea-example#3]
currently breaks - stops to slide. Also many dependencies are not fresh. Thanks!

**Comment by mariusandra** [comment]
Hey! I updated the example to use the latest kea and also most of the packages (all except `precss` and `react-hot-loader`). I'll get to the other ones this week.

**Comment by kn666** [comment]
That was fast! thank you )

**Comment by mariusandra** [comment]
Hey, even though I promised to update the rest of the dependencies this week, I will wait until Webpack 4 is out (planned for [end of Feburary](https://github.com/webpack/webpack/milestone/15)). That will require many bigger changes and it's better to do all of them together.

**Comment by kn666** [comment]
Hi! Time has come? )

**Comment by Ding-Fan** [comment]
Hi! Is there any update? I tried to find some example with function component but never found.

**Comment by mariusandra** [comment]
Hi, this repo is 3-4 years old by now and very outdated. I will archive this project and rename it to `kea-example-old-v0.27` or something like that.

If you would like to see real world examples using Kea, check out [PostHog](https://github.com/PostHog/posthog).
If you'd like to see a smaller self-contained example, check out the [Github API Tutorial](https://kea.js.org/docs/tutorials/github).
